name: Bake and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bake 
        run: docker run --rm -u jbake -v "$PWD":/mnt/site jbake/jbake:2.6.7
        #run: ./gradlew clean build buildDockerImage -x test -x dockerTest
      # - name: Push docker image
      #   run: |
      #     export CI_JOB_TIMESTAMP=$(date +%Y%m%dT%H%M%S)
      #     echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      #     docker images
      #     ./gradlew pushDockerImages
      #   if: ${{ github.ref == 'refs/heads/master' }}  
      #   env:
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #     DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      #     DOCKER_ACCOUNT: sogis
      #     DOCKER_REPO: ilivalidator-web-service
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      