name: Bake and Deploy
on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '5'
          cache: 'gradle'
      
      - name: Bake 
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install jbake 2.6.4
          jbake -b
      
      - name: Show files
        run: ls -la 
      
      # Upload Task ignoriert Subverzeichnisse.
      # - name: Upload files to S3
      #   run: ./gradlew upload
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      